### ISSUE TITLE
128x32 OLED display shows static

### ISSUE THREAD

**Issue by khn** [adafruit/Adafruit_SSD1305#2] opened 2016-02-09 00:03 UTC
When compiling for a 128x32, (after modification of the .h file and moving line 80 as described in prev issue) oled display only shows static. If I compile as a 128x64 display, I am able to see the display update, but, of course, not correctly. 
This seems to only be an issue with the 128x32 display. (https://www.adafruit.com/products/2675)

**Comment by wallen699** [comment] 2017-10-24 14:06
I too am having this issue - has this been resolved????

**Comment by aklofas** [comment] 2018-06-08 19:33
The problem is with line 189 in Adafruit_SSD1305.cpp
It should read SSD1305_128_32, not SSD1306_128_32
It doesn't seem like they actually tested this with a 128x32 :-/

**Comment by caternuson** [comment] 2019-12-05 23:52
Looks like there are multiple issues going on for the 128x32 display. Closing this issue so we can consolidate efforts in #12.

**Closed as completed by caternuson** 2019-12-05 23:52 UTC
